#!/bin/bash

# I use the Inconsolata font in this config, which you can find in ./fonts

## Operations ##
# Source this file to add these operations as bash shell functions

# Adds a bundle as a git submodule
function vim-bundle-add() {
  local url=$1
  local repo=${1##*/}
  local name=${repo%.git}

  pushd ~/.vim > /dev/null
  git submodule add $url bundle/$name
  git commit -m "Added bundle $name"
  popd > /dev/null
}

function vim-bundle-update() {
  # Updating a submodule
  git submodule update
  # OR
  # cd bundle/<module>
  # git pull

  #Remember to run this after you clone
  #
  #    $ git submodule init
  #    $ git submodule update
}

# Removes a bundle 
function vim-bundle-remove() {
  local bundle=bundle/${1%/}
  pushd ~/.vim > /dev/null
  git config -f .gitmodules --remove-section submodule.$bundle

  # Not sure this is necessary
  #git config -f .git/config --remove-section submodule.$bundle

  git rm --cached $bundle
  rm -rf $bundle
  git add .gitmodules
  git commit -m "Removed $1 bundle"
  popd > /dev/null
}

